interface Location {
  id: string;
  name: string;
  coordinates: {
    lat: number;
    lng: number;
  };
  description?: string;
  categories?: string[];
}

// Export tour as GPX format
export function exportAsGPX(locations: Location[], tourName: string): string {
  const timestamp = new Date().toISOString();

  let gpx = `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1"
  creator="Geo Story Tours"
  xmlns="http://www.topografix.com/GPX/1/1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">
  <metadata>
    <name>${escapeXml(tourName)}</name>
    <desc>Personalized walking tour generated by Geo Story Tours</desc>
    <time>${timestamp}</time>
  </metadata>
  <trk>
    <name>${escapeXml(tourName)}</name>
    <trkseg>
`;

  // Add track points
  locations.forEach((location) => {
    if (location.coordinates) {
      gpx += `      <trkpt lat="${location.coordinates.lat}" lon="${location.coordinates.lng}">
        <name>${escapeXml(location.name)}</name>
        <desc>${escapeXml(location.description || '')}</desc>
      </trkpt>
`;
    }
  });

  gpx += `    </trkseg>
  </trk>
`;

  // Add waypoints
  locations.forEach((location, index) => {
    if (location.coordinates) {
      gpx += `  <wpt lat="${location.coordinates.lat}" lon="${location.coordinates.lng}">
    <name>Stop ${index + 1}: ${escapeXml(location.name)}</name>
    <desc>${escapeXml(location.description || '')}</desc>
    <sym>Flag, Blue</sym>
  </wpt>
`;
    }
  });

  gpx += `</gpx>`;

  return gpx;
}

// Export tour as KML format
export function exportAsKML(locations: Location[], tourName: string): string {
  let kml = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${escapeXml(tourName)}</name>
    <description>Personalized walking tour generated by Geo Story Tours</description>

    <!-- Styles -->
    <Style id="tourLine">
      <LineStyle>
        <color>ff8B5CF6</color>
        <width>4</width>
      </LineStyle>
    </Style>
    <Style id="tourPoint">
      <IconStyle>
        <color>ff8B5CF6</color>
        <scale>1.2</scale>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/paddle/purple-circle.png</href>
        </Icon>
      </IconStyle>
    </Style>

    <!-- Route Line -->
    <Placemark>
      <name>Tour Route</name>
      <styleUrl>#tourLine</styleUrl>
      <LineString>
        <tessellate>1</tessellate>
        <coordinates>
`;

  // Add coordinates for the route line
  locations.forEach((location) => {
    if (location.coordinates) {
      kml += `          ${location.coordinates.lng},${location.coordinates.lat},0\n`;
    }
  });

  kml += `        </coordinates>
      </LineString>
    </Placemark>

    <!-- Tour Stops -->
`;

  // Add placemarks for each stop
  locations.forEach((location, index) => {
    if (location.coordinates) {
      kml += `    <Placemark>
      <name>Stop ${index + 1}: ${escapeXml(location.name)}</name>
      <description><![CDATA[
        <h3>${escapeXml(location.name)}</h3>
        <p>${escapeXml(location.description || '')}</p>
        ${location.categories ? `<p><strong>Categories:</strong> ${location.categories.join(', ')}</p>` : ''}
      ]]></description>
      <styleUrl>#tourPoint</styleUrl>
      <Point>
        <coordinates>${location.coordinates.lng},${location.coordinates.lat},0</coordinates>
      </Point>
    </Placemark>
`;
    }
  });

  kml += `  </Document>
</kml>`;

  return kml;
}

// Helper function to escape XML special characters
function escapeXml(unsafe: string): string {
  return unsafe
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

// Download file helper
export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

// Export tour in the specified format
export function exportTour(
  locations: Location[],
  tourName: string,
  format: 'gpx' | 'kml'
) {
  const timestamp = new Date().toISOString().split('T')[0];
  const sanitizedName = tourName.replace(/[^a-z0-9]/gi, '_').toLowerCase();

  if (format === 'gpx') {
    const gpxContent = exportAsGPX(locations, tourName);
    downloadFile(gpxContent, `${sanitizedName}_${timestamp}.gpx`, 'application/gpx+xml');
  } else if (format === 'kml') {
    const kmlContent = exportAsKML(locations, tourName);
    downloadFile(kmlContent, `${sanitizedName}_${timestamp}.kml`, 'application/vnd.google-earth.kml+xml');
  }
}
